# Generated by Django 2.2.4 on 2019-08-14 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_auto_20190814_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
    ]
